# Generated by Django 3.1.7 on 2021-05-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210521_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_table',
            old_name='job_desc',
            new_name='jobdesc',
        ),
        migrations.RenameField(
            model_name='register_table',
            old_name='job_email',
            new_name='jobemail',
        ),
        migrations.RenameField(
            model_name='register_table',
            old_name='job_name',
            new_name='jobname',
        ),
    ]
